services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: university_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
      target: production
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: your_username
      DB_PASSWORD: your_password
      DB_NAME: university_db
    networks:
      - app-network
    depends_on:
      - db
volumes:
  pgdata:

networks:
  app-network:
